---
- name: creating files or directories
  hosts: all
  become: true
  gather_facts: no

  tasks:
   - name: create a file
     file: 
       path: /home/ansadmin/testfile
       state: touch
       mode : 0755
       owner: ansadmin
       group: ansadmin
          
