































---
- name: installing packages
  hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: installing httpd package
    yum:
       name: httpd
       state: installed
  - name: starting service
    service: 
       name: httpd
       state: started
  - name: copying the file
    copy:
       src: /home/ansadmin/playbooks/index.html
       dest: /var/www/html

