---
- name: install and uninstall pkgs
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: multiple packages
      yum:
        name: "{{ item.pkg }}" 
        state: "{{ item.setup }}"
      loop:
         - { pkg: 'git', setup: 'installed' }
         - { pkg:  'make', setup: 'latest' } 
         - { pkg: 'wget', setup: 'installed' }
         - { pkg: 'tree', setup: 'absent' }     
