---
- name: creating user
  hosts: all
  become: true
  gather_facts: no
  
  tasks:
    - name: create user Megh
      user:
        name: Megh
    - name: create a directory
      file:
        path: /opt/Megh_tmp-dir
        state: directory
        owner: Megh
        group: Megh
        mode:  0755      

