---
- name: creating user
  hosts: all
  become: true
  gather_facts: no
  vars_files:
    - /home/ansadmin/playbooks/user.yml
  tasks:
    - name: create user {{ user_name }}
      user:
        name: "{{ user_name }}"
    - name: create a directory
      file:
        path: /opt/{{ user_name }}
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode:  0755

